# This is a basic workflow to help you get started with Actions

name: CSVToCSVW

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

#       - name: build csvtocsvw docker container
#         run: docker build --tag matolab:csvtocsvw https://raw.githubusercontent.com/Mat-O-Lab/CSVToCSVW/main/Dockerfile

#       # run the container 
#       - name: run csvtocsvw container app as demon
#         run: docker run -d -p 80:5000 matolab:csvtocsvw
#       # curl call to api endpoint
#       - name: example curl call to api endpoint
#         run: |
#           curl -X POST "http://localhost/api" -H  "accept: application/json" -H  \
#             "Content-Type: application/json" -d \
#             "{\"data_url\":\"https://raw.githubusercontent.com/Mat-O-Lab/resources/main/mechanics/data/polymer_tensile/Zugversuch_eng_ETFE-Ref%2BGroesseneffekt2.TRA\",\"separator\":\"auto\",\"encoding\":\"auto\"}"
      - name: echo workspace url
        run: echo ${{ github.workspace }}
      - name: Check changed files
        id: diff
        run: |
          # See https://github.community/t/check-pushed-file-changes-with-git-diff-tree-in-github-actions/17220/10
          export DIFF=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }} *.TRA)
          echo "$DIFF"
          # Escape newlines (replace \n with %0A)
          echo "::set-output name=diff::$( echo "$DIFF" | sed ':a;N;$!ba;s/\n/%0A/g' )"      
