# This is a basic workflow to help you get started with Actions

name: CSVToCSVW

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: build csvtocsvw docker container
        run: docker build -t matolab:csvtocsvw -f https://github.com/Mat-O-Lab/CSVToCSVW/raw/main/Dockerfile .

      # run the container 
      - name: run csvtocsvw container app
        run: docker run matolab:csvtocsvw
